version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "pass123"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "dev"
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./
    ports:
      - 8000:8000
    command: ${DOCKER_COMMAND}
    depends_on:
      - db
